package sbtwebjars

import sbt._
import sbt.Keys._
import sbt.librarymanagement.ConfigRef

/**
 * Adds a hidden `webjar` Ivy configuration for WebJar dependencies and
 * generates a type-safe Scala locator (`webjars.generated.WebJars`) from
 * the modules resolved under that configuration.
 *
 * Auto-enabled on every JVM project — no `enablePlugins(...)` needed.
 * Usage in build.sbt:
 *
 *   libraryDependencies ++= Seq(
 *     "org.webjars.npm" % "bootstrap" % "5.3.8" % Set(WebJar, Sass, Test),
 *     "org.webjars"     % "jquery"    % "3.7.1" % Set(WebJar, Test),
 *   )
 */
object WebJarsPlugin extends AutoPlugin {
  override def trigger  = allRequirements
  override def requires = sbt.plugins.JvmPlugin

  object autoImport {
    val WebJar = config("webjar").hide

    val webJarsPackage  = settingKey[String](
      "Package for the generated WebJars locator")
    val webJarsGenerate = taskKey[Seq[File]](
      "Generate a type-safe Scala locator for the WebJar-scoped deps")

    /**
     * Allows `% Set(WebJar, Sass, Test)` on a ModuleID. Defined here
     * rather than duplicated in `SassPlugin` so both plugins can
     * auto-enable without ambiguous-implicit errors.
     */
    implicit class ModuleIDOps(val m: ModuleID) extends AnyVal {
      def %(configs: Set[Configuration]): ModuleID =
        m.withConfigurations(Some(configs.map(_.name).mkString(",")))
    }
  }
  import autoImport._

  override def projectConfigurations: Seq[Configuration] = Seq(WebJar)

  override def projectSettings: Seq[Setting[_]] =
    inConfig(WebJar)(Defaults.configSettings) ++ Seq(
      ivyConfigurations += WebJar,
      webJarsPackage    := "webjars.generated",

      webJarsGenerate := {
        val log    = streams.value.log
        val pkg    = webJarsPackage.value
        val outDir = (Compile / sourceManaged).value / "webjars"
        val report = (WebJar / update).value

        val entries = report
          .configuration(ConfigRef(WebJar.name))
          .toSeq
          .flatMap(_.modules.map(_.module))
          .map(m => (m.organization, m.name, m.revision))
          .distinct
          .sortBy { case (g, a, _) => (g, a) }

        IO.createDirectory(outDir)
        val file = outDir / "WebJars.scala"
        IO.write(file, render(pkg, entries))
        log.info(s"[webjars] generated $file with ${entries.size} entries")
        Seq(file)
      },

      Compile / sourceGenerators += webJarsGenerate.taskValue,
    )

  private def render(pkg: String, entries: Seq[(String, String, String)]): String = {
    val cases = entries.map { case (g, a, v) =>
      val ident = if (a.matches("[A-Za-z][A-Za-z0-9]*")) a else s"`$a`"
      s"""    case $ident extends Artifact("$g", "$a", "$v")"""
    }.mkString("\n")

    s"""package $pkg
       |
       |// Generated by sbt-webjars. Do not edit.
       |object WebJars:
       |
       |  enum Artifact(val groupId: String, val name: String, val version: String):
       |$cases
       |
       |  def cdnUrl(a: Artifact, path: String): String =
       |    s"https://cdn.jsdelivr.net/webjars/$${a.groupId}/$${a.name}/$${a.version}/$$path"
       |
       |  def localUrl(a: Artifact, path: String): String =
       |    s"/webjars/$${a.name}/$${a.version}/$$path"
       |""".stripMargin
  }
}
