github.auth.token = ${?GITHUB_TOKEN}

oss.gpg-key = ${?OSS_GPG_KEY}
oss.gpg-pass = ${?OSS_GPG_PASS}
oss.deploy.username = ${?OSS_DEPLOY_USERNAME}
oss.deploy.password = ${?OSS_DEPLOY_PASSWORD}

webjars.file-service.url = ${?WEBJARS_FILE_SERVICE_URL}

maven.central.limit = ${?MAVEN_CENTRAL_LIMIT}
