github.auth.token = ${?GITHUB_TOKEN}

oss.gpg-key = ${?OSS_GPG_KEY}
oss.gpg-pass = ${?OSS_GPG_PASS}
oss.deploy.username = ${?OSS_DEPLOY_USERNAME}
oss.deploy.password = ${?OSS_DEPLOY_PASSWORD}

heroku.apikey = ${?HEROKU_API_KEY}

deploy.herokuapp = "webjars-test"
deploy.herokuapp = ${?DEPLOY_HEROKU_APP}
deploy.fork = ${?DEPLOY_FORK}

webjars.file-service.url = "https://webjars-file-service.herokuapp.com"
webjars.file-service.url = ${?WEBJARS_FILE_SERVICE_URL}
