package webjars.utils

import com.jamesward.zio_git.GitIgnore
import com.jamesward.zio_mavencentral.MavenCentral
import zio.*
import zio.compress.*
import zio.direct.*
import zio.stream.*

import java.nio.file.Paths

object WebJarCreator:

  private def parseExcludes(excludes: Iterable[String]): Either[Throwable, GitIgnore] =
    GitIgnore.parse(excludes).left.map(error => IllegalArgumentException(s"Invalid exclude pattern: $error"))

  def isExcluded(excludes: Set[String], name: String, isDirectory: Boolean): Boolean =
    parseExcludes(excludes).fold(throw _, _.isIgnored(name, isDirectory))

  def removeGlobPath(glob: String, path: String): Option[String] =
    val globParts = glob.split('/')
    val pathParts = path.split('/')
    if pathParts.length <= globParts.length then
      None
    else
      val parts = globParts.zip(pathParts)
      val removeGlob = parts.forall { case (g, s) => g == "*" || g == s }
      Option.when(removeGlob) {
        val reassembled = pathParts.drop(globParts.length).mkString("/")
        if path.endsWith("/") then reassembled + "/" else reassembled
      }

  /** Normalize an archive entry path by removing `.` segments and resolving
    * `..` segments. This guards against malformed source archives like the
    * `hookable` npm tarball (issue #2220) which contains entries such as
    * `package/./dist/index.cjs` alongside `package/dist/index.cjs`. The `./`
    * element causes JDK ZipFileSystem to reject the jar (JDK-8283486), and
    * the duplicate makes the resulting zip ambiguous.
    */
  def normalizeName(name: String): String =
    if name.isEmpty then name
    else
      val isDir = name.endsWith("/")
      val cleaned = name.split('/').foldLeft(Vector.empty[String]) { (acc, part) =>
        part match
          case "" | "." => acc
          case ".." if acc.nonEmpty && acc.last != ".." => acc.dropRight(1)
          case ".." => acc // drop unresolved leading `..` to avoid invalid zip entries
          case _ => acc :+ part
      }
      val joined = cleaned.mkString("/")
      if isDir && joined.nonEmpty then joined + "/" else joined

  private def fileEntry(path: String, contents: String): (ArchiveEntry[Option, Any], ZStream[Any, Throwable, Byte]) =
    (ArchiveEntry(name = path), ZStream.fromChunk(Chunk.fromArray(contents.getBytes)))

  private def dirEntry(path: String): (ArchiveEntry[Option, Any], ZStream[Any, Throwable, Byte]) =
    (ArchiveEntry(name = if path.endsWith("/") then path else path + "/", isDirectory = true), ZStream.empty)

  /** Detect ZIP/TAR and detach each entry's content before emitting it.
    * zio-streams-compress 2.x requires entry N to be fully consumed before N+1
    * is pulled; downstream transformations may buffer outer entries, so each
    * nested content stream is collected independently and then re-streamed. */
  def unarchiveStream(input: ZStream[Any, Throwable, Byte]): ZStream[Any, Throwable, (String, Boolean, Chunk[Byte])] =
    val branch = ZPipeline.branchAfter[Any, Throwable, Byte, (String, Boolean, Chunk[Byte])](2): prefix =>
      val restorePrefix = ZPipeline.prepend(prefix)
      val isZip = prefix.length >= 2 && (prefix(0) & 0xff) == 0x50 && (prefix(1) & 0xff) == 0x4b
      if isZip then
        restorePrefix >>> ZipUnarchiver.unarchive.mapZIO { case (entry, content) =>
          content.runCollect.map { bytes =>
            (entry.name, entry.isDirectory, bytes)
          }
        }
      else
        restorePrefix >>> TarUnarchiver.unarchive.mapZIO { case (entry, content) =>
          content.runCollect.map { bytes =>
            (entry.name, entry.isDirectory, bytes)
          }
        }

    input.via(branch)

  def createWebJar(input: ZStream[Any, Throwable, Byte], maybeBaseDirGlob: Option[String], exclude: Set[String], pom: String, webJarName: String, licenses: Set[License], groupId: MavenCentral.GroupId, artifactId: MavenCentral.ArtifactId, version: MavenCentral.Version, pathPrefix: String): Deployable.ArchiveStream =

    val webJarPrefix = s"META-INF/resources/webjars/$pathPrefix"

    val manifestLicense = licenses.flatMap { license =>
      (license.maybeName, license.maybeUrl) match
        case (Some(name), Some(url)) => Some(s"$name; $url")
        case (Some(name), None) => Some(name)
        case (None, Some(url)) => Some(url)
        case _ => None
    }.mkString(",")

    val manifest =
      s"""Manifest-Version: 1.0
         |Bundle-Description: WebJar for $webJarName
         |Bundle-License: $manifestLicense
         |Bundle-SymbolicName: $groupId.$artifactId
         |Bundle-Name: $webJarName
         |Bundle-Version: $version
         |Bundle-ManifestVersion: 2
         |Build-Jdk-Spec: 1.8
         |Created-By: webjars.org
         |""".stripMargin.replaceAll("\\r?\\n", "\r\n")

    val properties = s"""
        |#Generated by WebJar Sync
        |version=$version
        |groupId=$groupId
        |artifactId=$artifactId
       """.stripMargin

    val dirPaths = Iterator.iterate(Paths.get(webJarPrefix))(_.getParent).takeWhile(_ != null).toSeq.reverse

    val staticEntries: ZStream[Any, Throwable, (ArchiveEntry[Option, Any], ZStream[Any, Throwable, Byte])] =
      ZStream(fileEntry("META-INF/MANIFEST.MF", manifest)) ++
      ZStream.fromIterable(dirPaths.map(p => dirEntry(p.toString))) ++
      ZStream(
        fileEntry(s"META-INF/maven/$groupId/$artifactId/pom.xml", pom),
        fileEntry(s"META-INF/maven/$groupId/$artifactId/pom.properties", properties),
      )

    val transformedEntries: ZStream[Any, Throwable, (ArchiveEntry[Option, Any], ZStream[Any, Throwable, Byte])] =
      ZStream.unwrap:
        defer:
          val ignore = ZIO.fromEither(parseExcludes(exclude)).run
          // Track seen entry names so duplicates produced by malformed source
          // archives (e.g. `package/./foo` and `package/foo` both normalizing
          // to the same path — see issue #2220) are emitted only once.
          val seenNamesRef = Ref.make(Set.empty[String]).run
          unarchiveStream(input).mapZIO { case (entryName, isDir, content) =>
            val maybeNames = maybeBaseDirGlob.fold[Array[String]](Array(entryName)) { baseDirGlobs =>
              baseDirGlobs.split(',').flatMap { baseDirGlob =>
                removeGlobPath(baseDirGlob, entryName)
              }
            }

            val filteredNames = maybeNames
              .filter(name => !ignore.isIgnored(name, isDir))
              .map(normalizeName)
              .filter(_.nonEmpty)

            seenNamesRef.modify { seen =>
              val toEmit = filteredNames.filter(n => !seen.contains(webJarPrefix + n))
              (toEmit, seen ++ toEmit.map(webJarPrefix + _))
            }.map { uniqueNames =>
              if isDir then
                uniqueNames.toSeq.map { name =>
                  val path = webJarPrefix + name
                  (ArchiveEntry(name = path, isDirectory = true): ArchiveEntry[Option, Any], ZStream.empty: ZStream[Any, Throwable, Byte])
                }
              else
                uniqueNames.toSeq.map { name =>
                  val path = webJarPrefix + name
                  (ArchiveEntry(name = path): ArchiveEntry[Option, Any], ZStream.fromChunk(content): ZStream[Any, Throwable, Byte])
                }
            }
          }.flatMap(entries => ZStream.fromIterable(entries))

    (staticEntries ++ transformedEntries)
      .via(ZipArchiver.archive)
