package webjars.utils

import com.jamesward.zio_mavencentral.MavenCentral
import org.eclipse.jgit.ignore.IgnoreNode
import zio.*
import zio.compress.*
import zio.stream.*

import java.io.ByteArrayInputStream
import java.nio.file.Paths
import scala.annotation.tailrec

object WebJarCreator:

  @tailrec
  def isExcluded(excludes: Set[String], name: String, isDirectory: Boolean): Boolean =
    val ignoreNode = new IgnoreNode()
    val excludesInputStream = new ByteArrayInputStream(excludes.mkString("\n").getBytes)
    ignoreNode.parse(excludesInputStream)
    ignoreNode.isIgnored(name, isDirectory) match
      case IgnoreNode.MatchResult.IGNORED => true
      case IgnoreNode.MatchResult.NOT_IGNORED => false
      case IgnoreNode.MatchResult.CHECK_PARENT | IgnoreNode.MatchResult.CHECK_PARENT_NEGATE_FIRST_MATCH =>
        val parent = name.split("/").dropRight(1).mkString("/")
        if parent == "" then false
        else isExcluded(excludes, parent, true)

  def removeGlobPath(glob: String, path: String): Option[String] =
    val globParts = glob.split('/')
    val pathParts = path.split('/')
    if pathParts.length <= globParts.length then
      None
    else
      val parts = globParts.zip(pathParts)
      val removeGlob = parts.forall { case (g, s) => g == "*" || g == s }
      Option.when(removeGlob) {
        val reassembled = pathParts.drop(globParts.length).mkString("/")
        if path.endsWith("/") then reassembled + "/" else reassembled
      }

  /** Normalize an archive entry path by removing `.` segments and resolving
    * `..` segments. This guards against malformed source archives like the
    * `hookable` npm tarball (issue #2220) which contains entries such as
    * `package/./dist/index.cjs` alongside `package/dist/index.cjs`. The `./`
    * element causes JDK ZipFileSystem to reject the jar (JDK-8283486), and
    * the duplicate makes the resulting zip ambiguous.
    */
  def normalizeName(name: String): String =
    if name.isEmpty then name
    else
      val isDir = name.endsWith("/")
      val cleaned = name.split('/').foldLeft(Vector.empty[String]) { (acc, part) =>
        part match
          case "" | "." => acc
          case ".." if acc.nonEmpty && acc.last != ".." => acc.dropRight(1)
          case ".." => acc // drop unresolved leading `..` to avoid invalid zip entries
          case _ => acc :+ part
      }
      val joined = cleaned.mkString("/")
      if isDir && joined.nonEmpty then joined + "/" else joined

  private def fileEntry(path: String, contents: String): (ArchiveEntry[Option, Any], ZStream[Any, Throwable, Byte]) =
    (ArchiveEntry(name = path), ZStream.fromChunk(Chunk.fromArray(contents.getBytes)))

  private def dirEntry(path: String): (ArchiveEntry[Option, Any], ZStream[Any, Throwable, Byte]) =
    (ArchiveEntry(name = if path.endsWith("/") then path else path + "/", isDirectory = true), ZStream.empty)

  def unarchiveStream(input: ZStream[Any, Throwable, Byte]): ZStream[Any, Throwable, (String, Boolean, ZStream[Any, Throwable, Byte])] =
    ZStream.unwrap {
      input.runCollect.map { bytes =>
        val isZip = bytes.length >= 2 && (bytes(0) & 0xff) == 0x50 && (bytes(1) & 0xff) == 0x4b
        val byteStream = ZStream.fromChunk(bytes)
        if isZip then
          byteStream.via(ZipUnarchiver.unarchive).map { case (entry, content) =>
            (entry.name, entry.isDirectory, content: ZStream[Any, Throwable, Byte])
          }
        else
          byteStream.via(TarUnarchiver.unarchive).map { case (entry, content) =>
            (entry.name, entry.isDirectory, content: ZStream[Any, Throwable, Byte])
          }
      }
    }

  def createWebJar(input: ZStream[Any, Throwable, Byte], maybeBaseDirGlob: Option[String], exclude: Set[String], pom: String, webJarName: String, licenses: Set[License], groupId: MavenCentral.GroupId, artifactId: MavenCentral.ArtifactId, version: MavenCentral.Version, pathPrefix: String): ZIO[Any, Throwable, Array[Byte]] =

    val webJarPrefix = s"META-INF/resources/webjars/$pathPrefix"

    val manifestLicense = licenses.flatMap { license =>
      (license.maybeName, license.maybeUrl) match
        case (Some(name), Some(url)) => Some(s"$name; $url")
        case (Some(name), None) => Some(name)
        case (None, Some(url)) => Some(url)
        case _ => None
    }.mkString(",")

    val manifest =
      s"""Manifest-Version: 1.0
         |Bundle-Description: WebJar for $webJarName
         |Bundle-License: $manifestLicense
         |Bundle-SymbolicName: $groupId.$artifactId
         |Bundle-Name: $webJarName
         |Bundle-Version: $version
         |Bundle-ManifestVersion: 2
         |Build-Jdk-Spec: 1.8
         |Created-By: webjars.org
         |""".stripMargin.replaceAll("\\r?\\n", "\r\n")

    val properties = s"""
        |#Generated by WebJar Sync
        |version=$version
        |groupId=$groupId
        |artifactId=$artifactId
       """.stripMargin

    val dirPaths = Iterator.iterate(Paths.get(webJarPrefix))(_.getParent).takeWhile(_ != null).toSeq.reverse

    val staticEntries: ZStream[Any, Throwable, (ArchiveEntry[Option, Any], ZStream[Any, Throwable, Byte])] =
      ZStream(fileEntry("META-INF/MANIFEST.MF", manifest)) ++
      ZStream.fromIterable(dirPaths.map(p => dirEntry(p.toString))) ++
      ZStream(
        fileEntry(s"META-INF/maven/$groupId/$artifactId/pom.xml", pom),
        fileEntry(s"META-INF/maven/$groupId/$artifactId/pom.properties", properties),
      )

    val transformedEntries: ZStream[Any, Throwable, (ArchiveEntry[Option, Any], ZStream[Any, Throwable, Byte])] =
      ZStream.unwrap {
        // Track seen entry names so duplicates produced by malformed source
        // archives (e.g. `package/./foo` and `package/foo` both normalizing
        // to the same path — see issue #2220) are emitted only once.
        Ref.make(Set.empty[String]).map { seenNamesRef =>
          unarchiveStream(input).mapZIO { case (entryName, isDir, content) =>
            val maybeNames = maybeBaseDirGlob.fold[Array[String]](Array(entryName)) { baseDirGlobs =>
              baseDirGlobs.split(',').flatMap { baseDirGlob =>
                removeGlobPath(baseDirGlob, entryName)
              }
            }

            val filteredNames = maybeNames
              .filter(name => !isExcluded(exclude, name, isDir))
              .map(normalizeName)
              .filter(_.nonEmpty)

            seenNamesRef.modify { seen =>
              val toEmit = filteredNames.filter(n => !seen.contains(webJarPrefix + n))
              (toEmit, seen ++ toEmit.map(webJarPrefix + _))
            }.flatMap { uniqueNames =>
              if isDir then
                ZIO.succeed(uniqueNames.toSeq.map { name =>
                  val path = webJarPrefix + name
                  (ArchiveEntry(name = path, isDirectory = true): ArchiveEntry[Option, Any], ZStream.empty: ZStream[Any, Throwable, Byte])
                })
              else if uniqueNames.isEmpty then
                content.runDrain.as(Seq.empty)
              else if uniqueNames.length == 1 then
                ZIO.succeed(uniqueNames.toSeq.map { name =>
                  val path = webJarPrefix + name
                  (ArchiveEntry(name = path): ArchiveEntry[Option, Any], content)
                })
              else
                content.runCollect.map { bytes =>
                  uniqueNames.toSeq.map { name =>
                    val path = webJarPrefix + name
                    (ArchiveEntry(name = path): ArchiveEntry[Option, Any], ZStream.fromChunk(bytes): ZStream[Any, Throwable, Byte])
                  }
                }
            }
          }.flatMap(entries => ZStream.fromIterable(entries))
        }
      }

    (staticEntries ++ transformedEntries)
      .via(ZipArchiver.archive)
      .runCollect
      .map(_.toArray)
